### ISSUE TITLE
Form 2 convert

### ISSUE THREAD

**Issue by jaandk** [Hankintailmoitukset/hilma-migration#2]
When converting the attached form 2 to EstNoticeContract and then back the TED xml I observe some errors, please se below:

[Form2.txt](https://github.com/Hankintailmoitukset/hilma-migration/files/3863546/Form2.txt)

**Field:** Duration type
**Expected:**  Day 
**Result:** Month

**Field:** AddressReviceBody
**Expedted:**  <ADDRESS_REVIEW_INFO>
          <OFFICIALNAME>Konkurrence- og Forbrugerstyrelsen</OFFICIALNAME>
          <ADDRESS>Carl Jacobsens Vej 35</ADDRESS>
          <TOWN>Valby</TOWN>
          <POSTAL_CODE>2500</POSTAL_CODE>
          <COUNTRY VALUE="DK" />
          <PHONE>+45 41715000</PHONE>
          <E_MAIL>kfst@kfst.dk</E_MAIL>
          <FAX>+45 41715100</FAX>
          <URL>http://www.kfst.dk</URL>
        </ADDRESS_REVIEW_INFO>
        <DATE_DISPATCH_NOTICE>2018-09-03</DATE_DISPATCH_NOTICE>
**Result:** null

**Comment by tuomastolvanen** [comment]
Duration parsing should now work. 

The ADDRESS_REVIEW_INFO is not supported in the migration as this is not in use in finland.

**Comment by jaandk** [comment]
But ADDRESS_REVIEW_INFO is mandetory in TED for form2?

![Screenshot_99](https://user-images.githubusercontent.com/15653384/69407458-d1da5b00-0d04-11ea-9bd0-dfb17130dd74.png)

**Comment by tuomastolvanen** [comment]
ADDRESS_REVIEW_BODY is mandatory and it is supported notice.proceduresForReview.reviewBody, ADDRESS_REVIEW_INFO is not required and it is not currently supported.
