### ISSUE TITLE
Form 21 validation error

### ISSUE THREAD

**Issue by jaandk** [Hankintailmoitukset/hilma-migration#4]
When validating form 21 I get validation issue "Organisation.MainActivity" but schema validates correct agains TED validation rules. 
[Form21.txt](https://github.com/Hankintailmoitukset/hilma-migration/files/3864071/Form21.txt)

**Comment by tuomastolvanen** [comment]
Thanks for the report. This is a bug and the fix is coming

**Comment by tuomastolvanen** [comment]
This is now fixed in the latest version
